### PR TITLE
Pass --no-wrap to pandoc

### LINKED ISSUE #140: Funky line break in the "ad"
Why is this line break here? It is absent in the local html preview.

``` r
mean(rnorm(3))
#> [1] -0.4280615
```

Created on 2017-12-01 by the [reprex
package](http://reprex.tidyverse.org) (v0.1.1.9000).

### PR DESCRIPTION
**Pull request by jimhester**
Fixes #140

### CODE REVIEW

**Comment by jennybc** [comment]
Thanks! This is a better solution than I had brewing.

I'm going to hold off on merge until I can sort out why all hell broke loose on travis/appveyor.

**Comment by jimhester** [comment]
I think passing `--wrap=preserve` is actually a better fix than what I originally proposed, however from the travis failures it looks like it is a new option.

**Comment by jimhester** [comment]
I will figure out what the old option would be.

**Comment by jimhester** [comment]
So `--wrap=preserve` was [added in pandoc 1.16](https://github.com/jgm/pandoc/commit/536b6bf538a95f6db6ed41b72257f8b09fd26886), but travis is currently only using pandoc 1.15. 

So we will have to use `--no-wrap` for backwards compatibility I guess, unless you want to condition on `rmarkdown::pandoc_version()`

**Comment by jimhester** [comment]
Well that fixed the errors on travis, but appveyor has a bunch of failures, it is using [pandoc v1.13.1](https://ci.appveyor.com/project/tidyverse/reprex/build/1.0.221#L233) but it looks like `--no-wrap` was added [very early to pandoc](https://github.com/jgm/pandoc/commit/447b99e35d61b9379825b53906e5517964e20072) so not sure why they are failing.

**Comment by jennybc** [comment]
I have suffered from messing with other pandoc options in the past and had to back out. @jimhester How gross do you find my suggestion in #140 to deal with this post-render?

**Comment by jimhester** [comment]
pretty gross, I really think the pandoc option is the right fix, I can try to hunt down what is going on in appveyor tomorrow.

**Comment by jennybc** [comment]
@jimhester How about this? All the results aren't in yet ...

https://github.com/tidyverse/reprex/pull/146/files

**Comment by jimhester** [comment]
Yes, using non breaking spaces was my original fix. I _really_ think the pandoc option is the right thing to do.

**Comment by jennybc** [comment]
The older, now deprecated way to say this in pandoc is `--no-wrap`. But that [does not immediately clear things up on AppVeyor](https://github.com/tidyverse/reprex/pull/146/commits/58a7164596e8723c2d09e504d0a72ed386ca8585). I haven't delved into this yet at all, though.

**Comment by jennybc** [comment]
Oh, sorry, I see you had already done this and gotten same result.

**Comment by jimhester** [comment]
In c6d8f0c only one test fails on Appveyor, perhaps unrelated to these changes, so I think this is fixed.

**Comment by jimhester** [comment]
@jennybc does the current state of this PR look good to you? I am pretty confident this is the best way to fix this.

**Comment by jennybc** [comment]
Yes, thanks!

**Pull request merged**
