### PR TITLE
always specify html_file on render()

### PR DESCRIPTION
**Pull request by yutannihilation**
On Windows, I am jumped to browsers every time I execute `reprex()`. This is a bit annoying. This PR is a temporal workaround to let RStudio on Windows use Viwer Pane. Note that, I guess this is up to RStudio and is not the fault of reprex package, but I think we'll need this for a while.

According to this article, we have to place a HTML file in session temporary directory to render it in Viewer Pane:

> Note that the Viewer pane can only be used for local web content. This content can either be static HTML files written to the session temporary directory (i.e. files with paths generated by the tempfile function) or a locally run web application.
https://support.rstudio.com/hc/en-us/articles/202133558-Extending-RStudio-with-the-Viewer-Pane

But, currently, RStudio fails to recognize a tempdir is actually a tempdir, confused by the infamous ["8.3 short filename"](https://en.wikipedia.org/wiki/8.3_filename). I mean, `tempdir()` function returns a path in short form like this (given that my username is `username`), 

```r
"C:\\Users\\USERNA~1\\AppData\\Local\\Temp\\RtmpGSN3hM\\"
```

whereas `render()` returns the path in the ordinary form like this:

```r
"C:/Users/username/AppData/Local/Temp/RtmpGSN3hM/test_reprex_149c6f644b0d.html"
```

It seems that RStudio fails to recognize these two are the same.

### CODE REVIEW

**Comment by yutannihilation** [comment]
By the way, due to the lack of my R programming skill, I couldn't find a good reason to use this if statement... Shouldn't `html_file` be the same no matter the `outfile` is specified or not?

**Comment by jennybc** [comment]
Thanks! I had to refactor this a bit to account for other changes. I now pre-compute all filenames that might be needed and copy the html to the tempdir if it's not already there, before viewing. Can you check that I haven't just re-introduced your Windows problem?

**Comment by yutannihilation** [comment]
Thanks for the notice :) I confirmed everything works fine on my Windows now. Nice!

image

**Comment by jennybc** [comment]
Yay 🎉

**Pull request merged**
