### PR TITLE
Add gifs of reprex w datapasta

### PR DESCRIPTION
**Pull request by batpigandme**
I have the video footage too— the one with the spreadsheet is semi intolerable because the spreadsheet looks like it's toothpaste mint colored.

### CODE REVIEW

**Comment by jennybc** [comment]
Thanks! Do you have thoughts in where I should expose these? I could just merge to have them in the inventory. But I worry I / we will forget about them and maybe we should go ahead and add to an article or create an article or something. So they become link-able in conversations on slack, twitter, community, etc.

**Comment by batpigandme** [comment]
Agreed! I can easily write something up tomorrow. Ultimately I hope to have quick clips for a little decision tree of ways to  put data in a reprex - it's by far the most common point of confusion in community, and I'm hoping that 20 seconds of passive information consumption will be worth it if people know that this is precisely what they personally need to do.

**Comment by jennybc** [comment]
Sounds good. Just do your thing in additional commits in this PR then. I propose you make a new non-vignette article aimed at using reprex in concert with datapasta.

**Comment by batpigandme** [comment]
Hey Jenny,
So, I popped up a post here so I could see how video embeds looked next to the gifs: https://maraaverick.rbind.io/2018/10/reprex-with-datapasta/

The top gif (above) is super grainy, but it's also not mint green anymore on the spreadsheet (see below), so just let me know which you prefer. (I can't tell if the grainier version is comprehensible at this point because I've watched it so many times 😵).

**Comment by jennybc** [comment]
I think I prefer "sharp with touches of mint green".

**Comment by jennybc** [comment]
Thanks!

**Pull request merged**
